<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Mundipagg
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php
$_coreHelper    = $this->helper('core');
$_finalPrice    = Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal();
$_code          = $this->getMethodCode();
$api            = Mage::getModel('mundipagg/api');
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li style="display:none">
        <label for="<?php echo $_code ?>_cc_valor" class="required"><em>*</em><?php echo $this->__('Valor') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_valor" name="payment[cc_valor]" title="<?php echo $this->__('Valor') ?>" class="input-text" value="<?php echo $api->getValorTotal(); ?>" />
        </div>
    </li>
    <li>
        <div class="list-inline bandeiras_<?php echo $_code ?>">
            <span><i class="icon-bandeira icon-amex-off AE"></i></span>
            <span><i class="icon-bandeira icon-visa-off VI"></i></span>
            <span><i class="icon-bandeira icon-marter-card-off MC"></i></span>
            <span><i class="icon-bandeira icon-diners-off DN"></i></span>
            <span><i class="icon-bandeira icon-elo-off EL"></i></span>
            <span><i class="icon-bandeira icon-hipercard-off HI"></i></span>
        </div>
    </li>
    <li style="display:none">
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_parcelamento" class="required"><em>*</em><?php echo $this->__('Parcelamento'); ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_parcelamento" name="payment[cc_parcelamento]" title="<?php echo $this->__('Parcelamento') ?>" class="required-entry validate-type-select">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php $_ccParcelamento = $this->getInfoData('cc_parcelamento') ?>
                <?php foreach ($api->getInstallments() as $parcel): ?>
                    <option value="<?php echo $parcel['num'] ?>" <?php if ($parcel['num'] == $_ccParcelamento): ?> selected="selected"<?php endif ?>><?php echo $parcel['label'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" maxlength="16" onKeypress="mascara(this,sonumeros)"/>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" maxlength="30" placeholder="Nome impresso no cartão"/>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_cpf" class="required"><em>*</em><?php echo $this->__('CPF/CNPJ') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_cpf" name="payment[cc_cpf]" title="<?php echo $this->__('CPF/CNPJ') ?>" class="input-text" value="<?php echo $this->htmlEscape($this->getInfoData('cc_cpf')) ?>" onKeypress="mascara(this,mdocumento)" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="validate-cc-exp required-entry" style="width:100%">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k => $v): ?>
                        <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="required-entry"  style="width:100%">
                    <?php foreach ($this->getCcYears() as $k => $v): ?>
                        <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" maxlength="4" onKeypress="mascara(this,sonumeros)"/>
            </div>
            <a href="#" class="cvv-what-is-this"><i class="icon-bandeira icon-cod-seg ativo"></i></a>
        </div>
    </li>
    <?php endif; ?>
</ul>
<script type="text/javascript">
Validation.creditCartTypes.set('AE', [new RegExp('^3[47][0-9]{13}$'), new RegExp('^[0-9]{4}$'), true]);
Validation.creditCartTypes.set('VI', [new RegExp('^4[0-9]{12}([0-9]{3})?$'), new RegExp('^[0-9]{3}$'), true]);
Validation.creditCartTypes.set('MC', [new RegExp('^5[1-5][0-9]{14}$'), new RegExp('^[0-9]{3}$'), true]);
Validation.creditCartTypes.set('DN', [new RegExp('^3(?:0[0-5]|[68][0-9])[0-9]{11}$'), new RegExp('^[0-9]{3}$'), true]);
Validation.creditCartTypes.set('EL', [new RegExp('^([6362]{4})([0-9]{12})$'), new RegExp('^([0-9]{3})?$'), true]);
Validation.creditCartTypes.set('HI', [new RegExp('^(606282[0-9]{10})|(3841[0-9]{12})$'), new RegExp('^([0-9]{3})?$'), true]);
        
function selecionaBandeira(){
    jQuery('.bandeiras_<?php echo $_code ?>').find('i').removeClass('ativo');
    if(jQuery('#<?php echo $_code ?>_cc_number').val().length>=6){
        var cardType=formatoCartao(jQuery('#<?php echo $_code ?>_cc_number').val());
        jQuery('.bandeiras_<?php echo $_code ?>').find('i.'+cardType).addClass('ativo');
        jQuery('#<?php echo $_code ?>_cc_type').val(cardType);
    }
}

jQuery(function(){
    selecionaBandeira();
    jQuery('#<?php echo $_code ?>_cc_number').keyup(function(){
        selecionaBandeira();
    });
});

</script>