<?php
/**
 *
 * @category   Inovarti
 * @package    Inovarti_Mundipagg
 * @author     Suporte <suporte@inovarti.com.br>
 */
?>
<?php
$_coreHelper    = $this->helper('core');
$_finalPrice    = Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal();
$_code          = $this->getMethodCode();
$api            = Mage::getModel('mundipagg/api');
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li style="display:none">
        <label for="<?php echo $_code ?>_cc_valor" class="required"><em>*</em><?php echo $this->__('Valor') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_valor" name="payment[cc_valor]" title="<?php echo $this->__('Valor') ?>" class="input-text" value="<?php echo $api->getValorTotal(); ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_parcelamento" class="required"><em>*</em><?php echo $this->__('Parcelamento'); ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_parcelamento" name="payment[cc_parcelamento]" title="<?php echo $this->__('Parcelamento') ?>" class="required-entry">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php $_ccParcelamento = $this->getInfoData('cc_parcelamento') ?>
                <?php foreach ($api->getInstallments() as $parcel): ?>
                    <option value="<?php echo $parcel['num'] ?>" <?php if ($parcel['num'] == $_ccParcelamento): ?> selected="selected"<?php endif ?>><?php echo $parcel['label'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text required-entry" value="" maxlength="16" onKeypress="mascara(this,sonumeros)"/>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" maxlength="30" placeholder="Nome impresso no cartão"/>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_cpf" class="required"><em>*</em><?php echo $this->__('CPF/CNPJ') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_cpf" name="payment[cc_cpf]" title="<?php echo $this->__('CPF/CNPJ') ?>" class="input-text" value="<?php echo $this->htmlEscape($this->getInfoData('cc_cpf')) ?>" onKeypress="mascara(this,mdocumento)" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="validate-cc-exp required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k => $v): ?>
                        <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="required-entry">
                    <?php foreach ($this->getCcYears() as $k => $v): ?>
                        <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" maxlength="4"  onKeypress="mascara(this,sonumeros)"/>
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>
</ul>
